### ISSUE TITLE
windows下运行报错

### ISSUE THREAD

**Issue by xbotao** [kimown/hexoserver#1]
windows下运行报错

Botao Xiao@DESKTOP-BVLVNCM MINGW64 /e/WorkSpace/webProject/Hexo-Blog (master)
$ hexoserver
查找目录E:\WorkSpace\webProject\Hexo-Blog
installed yet
Starting server....
E:\WorkSpace\webProject\Hexo-Blog
[HPM] Proxy created: undefined  ->  http://localhost:4001
Listening at localhost:4001
Hash: 60818db8ed3d85387e09
Version: webpack 1.14.0
Time: 345ms
 Asset    Size  Chunks       Chunk Names
app.js  264 kB       0       app
chunk    {0} app.js (app) 224 kB [rendered]
    [0] multi app 52 bytes {0} [built] [1 error]
    [1] ./~/webpack-dev-server/client?http://localhost:4001 3.97 kB {0} [built]
    [2] ./~/url/url.js 22.3 kB {0} [built]
    [3] ./~/url/~/punycode/punycode.js 14.6 kB {0} [built]
    [4] ./~/webpack/buildin/module.js 251 bytes {0} [built]
    [5] ./~/querystring/index.js 127 bytes {0} [built]
    [6] ./~/querystring/decode.js 2.4 kB {0} [built]
    [7] ./~/querystring/encode.js 2.09 kB {0} [built]
    [8] ./~/strip-ansi/index.js 161 bytes {0} [built]
    [9] ./~/ansi-regex/index.js 135 bytes {0} [built]
   [10] ./~/webpack-dev-server/client/socket.js 856 bytes {0} [built]
   [11] ./~/sockjs-client/lib/entry.js 244 bytes {0} [built]
   [12] ./~/sockjs-client/lib/transport-list.js 613 bytes {0} [built]
   [13] ./~/sockjs-client/lib/transport/websocket.js 2.72 kB {0} [built]
   [14] ./~/process/browser.js 5.3 kB {0} [built]
   [15] ./~/sockjs-client/lib/utils/event.js 2 kB {0} [built]
   [16] ./~/sockjs-client/lib/utils/random.js 746 bytes {0} [built]
   [17] ./~/sockjs-client/lib/utils/browser-crypto.js 438 bytes {0} [built]
   [18] ./~/sockjs-client/lib/utils/url.js 975 bytes {0} [built]
   [19] ./~/url-parse/index.js 9.93 kB {0} [built]
   [20] ./~/requires-port/index.js 753 bytes {0} [built]
   [21] ./~/url-parse/lolcation.js 1.58 kB {0} [built]
   [22] ./~/querystringify/index.js 1.3 kB {0} [built]
   [23] ./~/debug/src/browser.js 4.71 kB {0} [built]
   [24] ./~/debug/src/debug.js 4.36 kB {0} [built]
   [25] ./~/ms/index.js 2.72 kB {0} [built]
   [26] ./~/inherits/inherits_browser.js 672 bytes {0} [built]
   [27] ./~/sockjs-client/lib/event/emitter.js 1.27 kB {0} [built]
   [28] ./~/sockjs-client/lib/event/eventtarget.js 1.85 kB {0} [built]
   [29] ./~/sockjs-client/lib/transport/browser/websocket.js 210 bytes {0} [built]
   [30] ./~/sockjs-client/lib/transport/xhr-streaming.js 1.25 kB {0} [built]
   [31] ./~/sockjs-client/lib/transport/lib/ajax-based.js 1.31 kB {0} [built]
   [32] ./~/sockjs-client/lib/transport/lib/sender-receiver.js 1.18 kB {0} [built]
   [33] ./~/sockjs-client/lib/transport/lib/buffered-sender.js 2.3 kB {0} [built]
   [34] ./~/sockjs-client/lib/transport/lib/polling.js 1.32 kB {0} [built]
   [35] ./~/sockjs-client/lib/transport/receiver/xhr.js 1.58 kB {0} [built]
   [36] ./~/sockjs-client/lib/transport/sender/xhr-cors.js 343 bytes {0} [built]
   [37] ./~/sockjs-client/lib/transport/browser/abstract-xhr.js 4.8 kB {0} [built]
   [38] ./~/sockjs-client/lib/transport/sender/xhr-local.js 352 bytes {0} [built]
   [39] ./~/sockjs-client/lib/utils/browser.js 560 bytes {0} [built]
   [40] ./~/sockjs-client/lib/transport/xdr-streaming.js 984 bytes {0} [built]
   [41] ./~/sockjs-client/lib/transport/sender/xdr.js 2.46 kB {0} [built]
   [42] ./~/sockjs-client/lib/transport/eventsource.js 766 bytes {0} [built]
   [43] ./~/sockjs-client/lib/transport/receiver/eventsource.js 1.58 kB {0} [built]
   [44] ./~/sockjs-client/lib/transport/browser/eventsource.js 37 bytes {0} [built]
   [45] ./~/sockjs-client/lib/transport/lib/iframe-wrap.js 981 bytes {0} [built]
   [46] ./~/sockjs-client/lib/transport/iframe.js 3.83 kB {0} [built]
   [47] ./~/json3/lib/json3.js 43.3 kB {0} [built]
   [48] ../Hexo-blog/~/webpack/buildin/amd-options.js 43 bytes {0} [built]
   [49] ./~/sockjs-client/lib/version.js 26 bytes {0} [built]
   [50] ./~/sockjs-client/lib/utils/iframe.js 5.03 kB {0} [built]
   [51] ./~/sockjs-client/lib/utils/object.js 532 bytes {0} [built]
   [52] ./~/sockjs-client/lib/transport/htmlfile.js 710 bytes {0} [built]
   [53] ./~/sockjs-client/lib/transport/receiver/htmlfile.js 2.2 kB {0} [built]
   [54] ./~/sockjs-client/lib/transport/xhr-polling.js 894 bytes {0} [built]
   [55] ./~/sockjs-client/lib/transport/xdr-polling.js 712 bytes {0} [built]
   [56] ./~/sockjs-client/lib/transport/jsonp-polling.js 1.02 kB {0} [built]
   [57] ./~/sockjs-client/lib/transport/receiver/jsonp.js 5.57 kB {0} [built]
   [58] ./~/sockjs-client/lib/transport/sender/jsonp.js 2.46 kB {0} [built]
   [59] ./~/sockjs-client/lib/main.js 11.9 kB {0} [built]
   [60] ./~/sockjs-client/lib/shims.js 17.2 kB {0} [built]
   [61] ./~/sockjs-client/lib/utils/escape.js 2.36 kB {0} [built]
   [62] ./~/sockjs-client/lib/utils/transport.js 1.35 kB {0} [built]
   [63] ./~/sockjs-client/lib/utils/log.js 450 bytes {0} [built]
   [64] ./~/sockjs-client/lib/event/event.js 477 bytes {0} [built]
   [65] ./~/sockjs-client/lib/location.js 177 bytes {0} [built]
   [66] ./~/sockjs-client/lib/event/close.js 295 bytes {0} [built]
   [67] ./~/sockjs-client/lib/event/trans-message.js 292 bytes {0} [built]
   [68] ./~/sockjs-client/lib/info-receiver.js 2.22 kB {0} [built]
   [69] ./~/sockjs-client/lib/transport/sender/xhr-fake.js 456 bytes {0} [built]
   [70] ./~/sockjs-client/lib/info-iframe.js 1.52 kB {0} [built]
   [71] ./~/sockjs-client/lib/info-iframe-receiver.js 791 bytes {0} [built]
   [72] ./~/sockjs-client/lib/info-ajax.js 1.03 kB {0} [built]
   [73] ./~/sockjs-client/lib/iframe-bootstrap.js 2.9 kB {0} [built]
   [74] ./~/sockjs-client/lib/facade.js 723 bytes {0} [built]
   [75] ./~/webpack/hot/dev-server.js 1.85 kB {0} [built]
   [76] ./~/webpack/hot/log-apply-result.js 813 bytes {0} [built]

```
ERROR in ./~/hexoserver/assets/app/index.js
Module parse failed: E:\WorkSpace\webProject\Hexo-Blog\node_modules\hexoserver\assets\app\index.js Unexpected token (9:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (9:4)
    at Parser.pp$4.raise (E:\WorkSpace\webProject\Hexo-blog\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\WorkSpace\webProject\Hexo-blog\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (E:\WorkSpace\webProject\Hexo-blog\node_modules\webpack\node_modules\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (E:\WorkSpace\webProject\Hexo-blog\node_modules\webpack\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (E:\WorkSpace\webProject\Hexo-blog\node_modules\webpack\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (E:\WorkSpace\webProject\Hexo-blog\node_modules\webpack\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (E:\WorkSpace\webProject\Hexo-blog\node_modules\webpack\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (E:\WorkSpace\webProject\Hexo-blog\node_modules\webpack\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExprList (E:\WorkSpace\webProject\Hexo-blog\node_modules\webpack\node_modules\acorn\dist\acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (E:\WorkSpace\webProject\Hexo-blog\node_modules\webpack\node_modules\acorn\dist\acorn.js:1741:35)
 @ multi app
webpack: Failed to compile.
```

**Comment by kimown** [comment]
window 是需要手动执行 `npm install hexoserver --save` 这个命令的

```
npm install npm -g
npm install hexo-cli -g
npm config set registry https://registry.npm.taobao.org  
hexo init blog
cd blog
hexo new mydemo
hexo g
npm install hexoserver-cli -g
npm install hexoserver --save
```
`npm config set registry https://registry.npm.taobao.org`加快下载速度的，推荐使用

不限定编辑器，不一定一定要用vi

这是我刚测试的截图


![untitled](https://cloud.githubusercontent.com/assets/7932380/23995776/f0143bb0-0a85-11e7-9449-61b4fba1ffac.gif)
